name: acdc
channels:
  - defaults
  - conda-forge
  - astropy
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - astropy
  - astroquery # from conda-forge
  - beautifulsoup4
  - requests
  - tqdm
  - lightkurve>=2.0 # from conda-forge
  - pandas
  - oktopus # from conda-forge channel
  - bokeh<2.3 # optional
  - jupyter
  - ipython
  - cython
  - scikit-learn
  - scikit-image
  - h5py
  - seaborn
  - astroplan
  - pip
  - pip:
      - corner
      - tess-point
